### PR TITLE
Check if Content-Type is application/json

### PR DESCRIPTION
**Pull request by vanruch**

### CODE REVIEW

**Comment by danihodovic** [comment]
What is the resulting HTTP status code and body when `throw new InvalidParametersError('application/json MIME type expected');` is called?

**Comment by vanruch** [comment]
@danihodovic just like any error:
```
status: 400,
body: {
    reason: "application/json MIME type expected"
}
```,
it's done in middlewares/error_handling.js

**Comment by danihodovic** [comment]
Cool :+1: 

Could we explicitly specify `The header Content-Type: application/json is required` ?

**Comment by vanruch** [comment]
https://github.com/jshttp/type-is 
It's probably same, but for readability it is a good idea

**Pull request merged**
