### PR TITLE
Merge master to dev

### PR DESCRIPTION
**Pull request by danihodovic**

### CODE REVIEW

**Comment by Anze1m** [comment]
Maybe firstly merge all open pull requests to dev, then merge master onto dev and then, finally dev onto master?

**Comment by danihodovic** [comment]
> Maybe firstly merge all open pull requests to dev, then merge master onto dev and then, finally dev onto master?

How long would merging the open PRs take? I would like to unblock master asap, ideally today.

**Comment by vanruch** [comment]
Done

**Comment by Anze1m** [comment]
Voila 😉

**Comment by danihodovic** [comment]
:100:

**Pull request merged**
